import React,{useEffect,useState,useRef} from 'react';
import {LayoutDashboard,Briefcase,Layers,Film,SlidersHorizontal,MessageSquare,Inbox,LogOut,Plus,Search,ArrowUpRight,Download,ShieldCheck,X,Trash2,ArrowUp,ArrowDown} from 'lucide-react';
import {PORTFOLIO_PROJECTS,SERVICES_LIST,REELS_DATA,BEFORE_AFTER_DATA} from '../data/mockData';
import './admin.css';
const defaults:Record<string,any[]>={portfolio:PORTFOLIO_PROJECTS,services:SERVICES_LIST,reels:REELS_DATA,beforeAfter:BEFORE_AFTER_DATA,testimonials:[]};
const sections=[['dashboard','Overview',LayoutDashboard],['leads','Enquiries',Inbox],['portfolio','Portfolio',Briefcase],['services','Services',Layers],['reels','Reels & videos',Film],['beforeAfter','Before / after',SlidersHorizontal],['testimonials','Client reviews',MessageSquare]] as const;
const schema:Record<string,Record<string,string|string[]>>={
 portfolio:{title:'Project title',industry:['FASHION','JEWELLERY','REAL ESTATE','PRODUCT','WEBSITES','SOCIAL MEDIA'],service:'Service delivered',description:'Description',image:'Image link',tags:'Tags (comma separated)'},
 services:{title:'Service name',shortDesc:'Description',category:['content','shoots','tech','growth','design'],icon:['Share2','Sparkles','Film','Camera','Video','Users','TrendingUp','Globe','Smartphone','Sliders','Scissors','Palette','UserCheck','ClipboardCheck','Tv'],popular:'Featured service'},
 reels:{title:'Video title',category:['Fashion','Jewellery','Real Estate','Beauty','Products','Business Promotions'],description:'Description',thumbnail:'Cover image link',videoUrl:'Direct video link (MP4)',tag:'Short label'},
 beforeAfter:{title:'Example title',category:'Editing service',description:'Description',beforeImage:'Before image link',afterImage:'After image link',beforeLabel:'Before label',afterLabel:'After label'},
 testimonials:{name:'Client name',company:'Company',quote:'Approved review'}
};
const statuses=['New','Contacted','In progress','Completed','Archived'];
async function api(action:string,body?:any){const r=await fetch('/api/admin?action='+action,{method:body?'POST':'GET',headers:body?{'Content-Type':'application/json'}:undefined,body:body?JSON.stringify(body):undefined});let d;try{d=await r.json();}catch{throw new Error('Start the project with the API server. See ADMIN_SETUP.md.');}if(!r.ok)throw new Error(d.message||'Request failed');return d;}
function download(data:unknown,name:string){const url=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
export function Admin(){
 const dialogRef=useRef<HTMLElement>(null);
 const [user,setUser]=useState<string|null>(null),[checking,setChecking]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('');
 const [tab,setTab]=useState('dashboard'),[search,setSearch]=useState(''),[filter,setFilter]=useState('All');
 const [content,setContent]=useState<Record<string,any[]>>(defaults),[versions,setVersions]=useState<Record<string,number>>({}),[leads,setLeads]=useState<any[]>([]),[loaded,setLoaded]=useState(false);
 const [editing,setEditing]=useState<any>(null),[lead,setLead]=useState<any>(null);
 useEffect(()=>{
  if(!editing&&!lead)return;
  const previous=document.activeElement as HTMLElement;
  const selector='button:not([disabled]),input,textarea,select,a[href]';
  const frame=requestAnimationFrame(()=>dialogRef.current?.querySelector<HTMLElement>('input,textarea,select,button')?.focus());
  const handle=(e:KeyboardEvent)=>{if(e.key==='Escape'&&!busy){setEditing(null);setLead(null);}if(e.key==='Tab'){const nodes=Array.from(dialogRef.current?.querySelectorAll<HTMLElement>(selector)||[]);const first=nodes[0],last=nodes[nodes.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last?.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first?.focus();}}};
  const old=document.body.style.overflow;document.body.style.overflow='hidden';document.addEventListener('keydown',handle);
  return()=>{cancelAnimationFrame(frame);document.removeEventListener('keydown',handle);document.body.style.overflow=old;previous?.focus();};
 },[Boolean(editing),Boolean(lead),busy]);
 useEffect(()=>{api('session').then(d=>setUser(d.email)).catch(e=>{if(!e.message.includes('sign in'))setError(e.message);}).finally(()=>setChecking(false));},[]);
 useEffect(()=>{if(user)load();},[user]);
 async function load(){setBusy(true);setError('');try{const [rows,ls]=await Promise.all([api('content'),api('leads')]);const next={...defaults},v:Record<string,number>={};for(const row of rows){next[row.key]=row.items??defaults[row.key];v[row.key]=row.version;}setContent(next);setVersions(v);setLeads(ls);setLoaded(true);}catch(e){setError(e.message);}finally{setBusy(false);}}
 async function login(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);setBusy(true);setError('');try{const d=await api('login',{email:f.get('email'),password:f.get('password')});setUser(d.email);}catch(e){setError(e.message);}finally{setBusy(false);}}
 async function save(items:any[]){setBusy(true);setError('');setNotice('');try{const r=await api('content',{key:tab,items,version:versions[tab]});setContent({...content,[tab]:r.items});setVersions({...versions,[tab]:r.version});setEditing(null);setNotice('Saved. Website visitors will see this content on their next page load.');return true;}catch(e){setError(e.message);return false;}finally{setBusy(false);}}
 async function saveEditor(e:React.FormEvent<HTMLFormElement>){e.preventDefault();if(tab==='testimonials' && !window.confirm('Do you have the client’s approval to publish this review?'))return;const items=[...content[tab]],i=items.findIndex(x=>x.id===editing.id);if(i<0)items.push(editing);else items[i]=editing;await save(items);}
 async function saveLead(e:React.FormEvent){e.preventDefault();setBusy(true);setError('');try{const saved=await api('leads',{id:lead.id,status:lead.status,notes:lead.notes});setLeads(leads.map(l=>l.id===saved.id?saved:l));setLead(null);setNotice('Enquiry updated.');}catch(e){setError(e.message);}finally{setBusy(false);}}
 function move(id:string,dir:number){const items=[...content[tab]],i=items.findIndex(x=>x.id===id),j=i+dir;if(j<0||j>=items.length)return;[items[i],items[j]]=[items[j],items[i]];save(items);}
 function add(){const item:any={id:crypto.randomUUID()};Object.entries(schema[tab]).forEach(([k,v])=>item[k]=k==='tags'?[]:k==='popular'?false:Array.isArray(v)?v[0]:'');setEditing(item);setError('');}
 const filteredLeads=leads.filter(l=>(filter==='All'||l.status===filter)&&[l.full_name,l.email,l.phone,l.service,l.brand,l.ticket_id].join(' ').toLowerCase().includes(search.toLowerCase()));
 if(checking)return <div className="nl-admin nl-center"><p>Opening your workspace…</p></div>;
 if(!user)return <div className="nl-admin nl-login"><div className="nl-login-brand"><img src="/logo.png" alt="Nexa Loops"/><p>YOUR CREATIVE BUSINESS, ORGANIZED.</p><h1>Good work.<br/>Great control.</h1><p>Manage your work, keep conversations moving and make your next update.</p></div><form className="nl-login-form" onSubmit={login}><ShieldCheck size={32}/><span className="nl-eyebrow">NEXA LOOPS / ADMIN</span><h2>Welcome back.</h2><p>Sign in with your owner account.</p>{error&&<div role="alert" className="nl-error">{error}</div>}<label>Email address<input name="email" type="email" autoComplete="username" placeholder="Your admin email" required/></label><label>Password<input name="password" type="password" autoComplete="current-password" required/></label><button className="nl-primary" disabled={busy}>{busy?'Signing in…':'Sign in to workspace'} <ArrowUpRight size={18}/></button><p className="nl-muted">Owner access only. For first-time setup or a password reset, see ADMIN_SETUP.md in your website files.</p><a href="/">Back to website</a></form></div>;
 return <div className="nl-admin nl-shell"><aside className="nl-sidebar"><a className="nl-brand" href="/"><img src="/logo.png" alt=""/><span><b>Nexa <em>Loops</em></b><small>BUSINESS WORKSPACE</small></span></a><div className="nl-eyebrow">MANAGE</div><nav>{sections.map(([key,label,Icon])=><button key={key} aria-current={tab===key?'page':undefined} onClick={()=>{setTab(key);setSearch('');setFilter('All');setNotice('');setError('');}} className={tab===key?'active':''}><Icon size={19}/>{label}{key==='leads'&&<span className="nl-count">{leads.filter(l=>l.status==='New').length}</span>}</button>)}</nav><div className="nl-owner"><ShieldCheck size={20}/><div><b>Owner workspace</b><small>{user}</small></div></div><button onClick={async()=>{try{await api('logout',{});setUser(null);setLeads([]);setContent(defaults);setLoaded(false);}catch(e){setError(e.message);}}}><LogOut size={18}/> Sign out</button></aside>
 <div className="nl-work"><header className="nl-topbar"><span>Nexa Loops <span className="nl-muted">/ {sections.find(s=>s[0]===tab)?.[1]}</span></span><a href="/" target="_blank" rel="noreferrer">View website <ArrowUpRight size={16}/></a></header><main className="nl-main"><div className="nl-heading"><div><span className="nl-eyebrow">YOUR STUDIO, AT A GLANCE</span><h1>{tab==='dashboard'?'Workspace overview':sections.find(s=>s[0]===tab)?.[1]}</h1><p>{tab==='dashboard'?'A clear view of your enquiries and published work.':tab==='leads'?'Track each conversation from first enquiry to completed work.':'Update the content shown on your website.'}</p></div><div className="nl-actions">{tab==='dashboard'?<button onClick={load} disabled={busy}>{busy?'Loading…':'Refresh'}</button>:tab==='leads'?<button disabled={!loaded} onClick={()=>download(filteredLeads,'Nexa_Loops_Enquiries.json')}><Download size={17}/>Export</button>:<button disabled={busy||!loaded} className="nl-primary" onClick={add}><Plus size={18}/>Add {tab==='testimonials'?'review':'item'}</button>}</div></div>
 {error&&<div role="alert" className="nl-error">{error} {!loaded&&<button onClick={load}>Retry</button>}</div>}{notice&&<div role="status" className="nl-notice">{notice}</div>}
 {!loaded?<section className="nl-panel"><p>{busy?'Loading your workspace…':'Connect the database to load and manage your content.'}</p></section>:tab==='dashboard'?<><div className="nl-stats">{[['New enquiries',leads.filter(l=>l.status==='New').length,'Waiting for your reply'],['Active conversations',leads.filter(l=>['Contacted','In progress'].includes(l.status)).length,'Keep the next step moving'],['Portfolio projects',content.portfolio.length,'Current website collection'],['Services',content.services.length,'Available to your clients']].map(([label,num,desc])=><section className="nl-stat" key={label}><span>{label}</span><strong>{num}</strong><small>{desc}</small></section>)}</div><div className="nl-dashboard-grid"><section className="nl-panel"><div className="nl-panel-title"><h2>Recent enquiries</h2><button onClick={()=>setTab('leads')}>View all <ArrowUpRight size={15}/></button></div>{leads.length?leads.slice(0,5).map(l=><button className="nl-lead-row" key={l.id} onClick={()=>setLead({...l})}><span className="nl-avatar">{l.full_name.slice(0,1)}</span><span><b>{l.full_name}</b><small>{l.service}</small></span><span className="nl-badge">{l.status}</span></button>):<div className="nl-empty"><Inbox size={36}/><h3>Your next conversation starts here.</h3><p>Enquiries submitted through your connected website will appear here.</p><a href="/contact" target="_blank" rel="noreferrer">Open enquiry form <ArrowUpRight size={16}/></a></div>}</section><section className="nl-panel nl-blue"><span className="nl-eyebrow">KEEP YOUR WORK CURRENT</span><h2>Make room for<br/>your next project.</h2><p>Add your latest work and give future clients a reason to get in touch.</p><button onClick={()=>setTab('portfolio')}>Manage portfolio <ArrowUpRight size={17}/></button><div className="nl-divider"/><p>Content backup</p><button onClick={()=>download(content,'Nexa_Loops_Content_Backup.json')}><Download size={16}/>Download JSON</button></section></div><div className="nl-footnote">Existing website examples remain until you replace or remove them. Publish only your own work and approved client reviews.</div></>:<>
 <div className="nl-toolbar"><label className="nl-search"><Search size={18}/><input aria-label="Search entries" placeholder={tab==='leads'?'Search name, phone, service…':'Search this collection…'} value={search} onChange={e=>setSearch(e.target.value)}/></label>{tab==='leads'&&<select aria-label="Filter by status" value={filter} onChange={e=>setFilter(e.target.value)}>{['All',...statuses].map(s=><option key={s}>{s}</option>)}</select>}<span className="nl-muted">{tab==='leads'?filteredLeads.length:content[tab].length} items</span></div>
 {tab==='leads'?<section className="nl-panel nl-table-wrap"><table><thead><tr><th>Client</th><th>Service</th><th>Received</th><th>Status</th><th>Details</th></tr></thead><tbody>{filteredLeads.map(l=><tr key={l.id}><td><b>{l.full_name}</b><small>{l.phone}</small></td><td>{l.service}</td><td>{new Date(l.created_at).toLocaleDateString('en-IN')}</td><td><span className="nl-badge">{l.status}</span></td><td><button onClick={()=>{setLead({...l});setError('');}}>Open</button></td></tr>)}</tbody></table>{!filteredLeads.length&&<div className="nl-empty"><Inbox/><p>No enquiries match this view.</p></div>}<p className="nl-footnote">Showing up to 1,000 most recent enquiries.</p></section>:<><p className="nl-footnote">Use direct HTTPS links for images and MP4 videos. Saving updates the website collection immediately.</p><div className="nl-cards">{content[tab].filter(item=>JSON.stringify(item).toLowerCase().includes(search.toLowerCase())).map(item=><article className="nl-card" key={item.id}>{(item.image||item.thumbnail||item.beforeImage)&&<img className="nl-cover" src={item.image||item.thumbnail||item.beforeImage} alt={item.title} loading="lazy"/>}<div className="nl-card-body"><span className="nl-eyebrow">{item.industry||item.category||item.company||'CLIENT REVIEW'}</span><h2>{item.title||item.name}</h2><p>{item.shortDesc||item.description||item.quote}</p><div className="nl-card-actions"><button onClick={()=>{setEditing({...item});setError('');}}>Edit</button><button aria-label="Move up" disabled={busy||content[tab][0].id===item.id} onClick={()=>move(item.id,-1)}><ArrowUp size={16}/></button><button aria-label="Move down" disabled={busy||content[tab].at(-1)?.id===item.id} onClick={()=>move(item.id,1)}><ArrowDown size={16}/></button><button aria-label={'Delete '+(item.title||item.name)} disabled={busy} className="nl-danger" onClick={()=>{if(window.confirm('Remove this item from the website?'))save(content[tab].filter(x=>x.id!==item.id));}}><Trash2 size={16}/></button></div></div></article>)}</div>{!content[tab].length&&<section className="nl-panel nl-empty"><Plus size={32}/><h3>No items yet</h3><p>Add your first {tab==='testimonials'?'approved review':'item'}.</p></section>}</>}
 </>}
 </main></div>
 {(editing||lead)&&<div className="nl-overlay"><section ref={dialogRef} role="dialog" aria-modal="true" aria-label={lead?'Enquiry details':'Edit website content'} className="nl-dialog"><button className="nl-close" aria-label="Close editor" disabled={busy} onClick={()=>{setEditing(null);setLead(null);}}><X/></button><span className="nl-eyebrow">NEXA LOOPS / {lead?'ENQUIRY':'CONTENT EDITOR'}</span><h2>{lead?lead.full_name:(editing.title||editing.name||'New item')}</h2>{error&&<p className="nl-error" role="alert">{error}</p>}{lead?<form onSubmit={saveLead}><p className="nl-muted">{lead.ticket_id} · {new Date(lead.created_at).toLocaleString('en-IN')}</p><dl>{[['Phone',lead.phone],['Email',lead.email||'Not provided'],['Brand',lead.brand||'Not provided'],['Service',lead.service],['Budget',lead.budget],['Timeline',lead.timeline],['Message',lead.message]].map(([k,v])=><div key={k}><dt>{k}</dt><dd>{v}</dd></div>)}</dl><label>Status<select value={lead.status} onChange={e=>setLead({...lead,status:e.target.value})}>{statuses.map(s=><option key={s}>{s}</option>)}</select></label><label>Private follow-up notes<textarea maxLength={3000} value={lead.notes} onChange={e=>setLead({...lead,notes:e.target.value})}/></label><button className="nl-primary" disabled={busy}>{busy?'Saving…':'Save enquiry'}</button></form>:<form onSubmit={saveEditor}>{Object.entries(schema[tab]).map(([key,label])=><label key={key}>{Array.isArray(label)?key==='icon'?'Service icon':key==='industry'?'Industry':'Category':label}{key==='popular'?<input type="checkbox" checked={editing[key]} onChange={e=>setEditing({...editing,[key]:e.target.checked})}/>:Array.isArray(label)?<select value={editing[key]} onChange={e=>setEditing({...editing,[key]:e.target.value})}>{label.map(v=><option key={v}>{v}</option>)}</select>:['description','shortDesc','quote'].includes(key)?<textarea required maxLength={3000} value={editing[key]||''} onChange={e=>setEditing({...editing,[key]:e.target.value})}/>:<input autoFocus={key===Object.keys(schema[tab])[0]} required={!['tags','company','beforeLabel','afterLabel','tag'].includes(key)} maxLength={3000} value={key==='tags'?editing[key].join(','):editing[key]||''} onChange={e=>setEditing({...editing,[key]:key==='tags'?e.target.value.split(','):e.target.value})}/>}</label>)}<div className="nl-editor-footer"><button type="button" disabled={busy} onClick={()=>setEditing(null)}>Cancel</button><button className="nl-primary" disabled={busy}>{busy?'Saving…':'Save to website'}</button></div></form>}</section></div>}
 </div>;
}
